<p>Para lanzar una excepción hay que instanciar un objeto del tipo de la excepción que se quiera lanzar y utilizar un comando para lanzarla. Opcionalmente se puede añadir un mensaje de error.</p>

<p>Por ejemplo:</p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/4/<lenguaje>/0.<lenguaje>"></pre>
</div>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/4/<lenguaje>/1.<lenguaje>"></pre>
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/4/<lenguaje>/1.txt"></pre>
</div>

<p>Las excepciones, si no se capturan, son propagadas hasta detener la ejecución completamente.</p>

<p>En el siguiente ejemplo, la excepción se produce en el método <code>fija_temperatura</code> que es lanzada al constructor y desde el constructor propagada al programa principal donde se interrumpe la ejecución.</p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/4/<lenguaje>/2.<lenguaje>"></pre>
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/4/<lenguaje>/2.txt"></pre>
</div>

<p>En el siguiente ejemplo, se añade control de la excepción en el constructor fijando la temperatura a 0 en caso de producirse alguna excepción.</p>

<div class="container">
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/4/<lenguaje>/3.<lenguaje>"></pre>
    <pre data-code="https://raw.githubusercontent.com/klippero/code-snippet-in-web/refs/heads/main/POO/temas/31/4/3.txt"></pre>
</div>
